# Generated by Django 6.0 on 2025-12-17 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_commits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeterritory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.employee'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='commit',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='configapp.news'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.category'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.supplier'),
        ),
        migrations.AddField(
            model_name='territory',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.region'),
        ),
        migrations.AddField(
            model_name='employeeterritory',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.territory'),
        ),
    ]
